work_dir: ./work_dir/FER/AFEW/PST-BLN-bone
model_saved_name: ./FER/AFEW/PST-BLN-bone
results_file_name: ./results/AFEW/AFEW_PSTBLN_bone_mcdo_results.txt
MonteCarloDropOut: True
MCDO_repeats: 100
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ../data/AFEW/Aug_Train_bone.npy
  label_path: ../data/AFEW/Aug_train_labels.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../data/AFEW/norm_Val_bone.npy
  label_path: ../data/AFEW/val_labels.pkl

# model
model: model.stbln_mcdo.Model
old_model_path: ./runs/
numlayers: 20
numblocks: 50
model_args:
  topology: []
  blocksize: 5
  num_class: 7
  num_point: 312
  num_person: 1
  graph: graph.AFEW.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [3000]

# training
device: [0,1,2,3]
batch_size: 128
test_batch_size: 128
num_epoch: 300 
nesterov: True
