# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ../data/AFEW/norm_Val_bone.npy
  label_path: ../data/AFEW/val_labels.pkl
  debug: False

# model
model: model.stbln.STBLN
model_name: STBLN
model_args:
  num_class: 7
  num_point: 312
  num_person: 1

# test 
phase: test
device: [0]
test_batch_size: 256
weights: ./runs/trianloss/STBLN_7_1.pt # here put the path to the pre-trained model

work_dir: ./work_dir/FER/AFEW/STBLN
model_saved_name: ./FER/AFEW/STBLN
save_score: True
