work_dir: ./work_dir/FER/CK/PSTBLN_bone_mcdo_5
model_saved_name: ./FER/CK/PSTBLN_bone_mcdo_5
results_file_name: ./results/CK/CK_PSTBLN_bone_mcdo_results_5.txt
MonteCarloDropOut: True
MCDO_repeats: 100
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ../data/CK+/10fold/Train_bone_5.npy
  label_path: ../data/CK+/10fold/Train_labels5.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../data/CK+/10fold/Val_bone_5.npy
  label_path: ../data/CK+/10fold/Val_labels5.pkl

# model
model: model.pstbln.PSTBLN
model_name: PSTBLN
old_model_path: ./runs/
numlayers: 20
numblocks: 50
model_args:
  topology: []
  blocksize: 5
  num_class: 7
  num_point: 303
  num_person: 1

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [3000]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 350
nesterov: True
