work_dir: ./work_dir/FER/CASIA/STBLN_bone_mcdo_1
model_saved_name: ./FER/CASIA/STBLN_bone_mcdo_1
results_file_name: ./results/CASIA/CASIA_STBLN_bone_mcdo_results_1.txt
MonteCarloDropOut: True
MCDO_repeats: 100
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ../data/CASIA/Train_bone_1.npy
  label_path: ../data/CASIA/train_labels1.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../data/CASIA/Val_bone_1.npy
  label_path: ../data/CASIA/val_labels1.pkl

# model
model: model.stbln.STBLN
model_name: STBLN
old_model_path: ./runs/
model_args:
  num_class: 6
  num_point: 309
  num_person: 1

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [3000]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 350
nesterov: True
