# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ../data/CASIA/10fold/Val_bone_1.npy
  label_path: ../data/CASIA/10fold/Val_labels1.pkl
  debug: False

# model
model: model.stbln.STBLN
model_name: STBLN
model_args:
  num_class: 6
  num_point: 309
  num_person: 1

# test 
phase: test
device: [0]
test_batch_size: 256
weights: ./runs/trianloss/STBLN_bone_mcdo_1.pt # here put the path to the pre-trained model

work_dir: ./work_dir/FER/CASIA/STBLN_bone_mcdo_0
model_saved_name: ./FER/CASIA/STBLN_bone_mcdo_0
save_score: True
